module Stupidedi
  module Contrib
    module FortyTen
      module Guides
        module Wayfair

          b = GuideBuilder
          d = Schema
          r = SegmentReqs
          e = ElementReqs
          s = Versions::FunctionalGroups::FortyTen::SegmentDefs
          t = Contrib::FortyTen::TransactionSetDefs

          #
          # Purchase Order
          #
          PO850 =
            b.build(t::PO850,
                    d::TableDef.header("Heading",
                                       b::Segment(10, s:: ST, "Transaction Set Header",
                                                  r::Required, d::RepeatCount.bounded(1),
                                                  b::Element(e::Required,    "Transaction Set Identifier Code", b::Values("850")),
                                                  b::Element(e::Required,    "Transaction Set Control Number")),

                                       b::Segment(20, s::BEG, "Beginning Segment for Purchase Order",
                                                  r::Required, d::RepeatCount.bounded(1),
                                                  b::Element(e::Required,    "Transaction Set Purpose Code", b::Values("00")),
                                                  b::Element(e::Required,    "Purchase Order Type Code", b::Values("DS", "CO", "PR", "OS", "RC")),
                                                  b::Element(e::Required,    "Purchase Order Number"),
                                                  b::Element(e::Situational, "Release Number"),
                                                  b::Element(e::Required,    "Date"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A")),
                                       b::Segment(50, s::REF, "Reference Identification",
                                                  r::Situational, d::RepeatCount.unbounded,
                                                  b::Element(e::Required,    "Reference ID Qualifier", b::Values("VR")),
                                                  b::Element(e::Situational, "Reference ID"),
                                                  b::Element(e::Situational, "Description (WH ZIP)"),
                                                  b::Element(e::NotUsed,     "N/A")),
                                       b::Segment(60, s::PER, "Administrative Communications Contact",
                                                  r::Situational, d::RepeatCount.bounded(3),
                                                  b::Element(e::Required,    "Contact Function Code", b::Values("IC")),
                                                  b::Element(e::Situational, "Name"),
                                                  b::Element(e::Situational, "Communication Number Qualifier", b::Values("FX")),
                                                  b::Element(e::Situational, "Communication Number"),
                                                  b::Element(e::Situational, "Communication Number Qualifier", b::Values("TE")),
                                                  b::Element(e::Situational, "Communication Number"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A"),
                                                  b::Element(e::NotUsed,     "N/A")),
                                       b::Segment(70, s::FOB, "FOB Related Instructions",
                                                  r::Situational, d::RepeatCount.bounded(1),
                                                  b::Element(e::Required, "Shipment - Method of Payment", b::Values("PP", "PC", "TP")),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A")),
                                       b::Segment(80, s::CTP, "CTP",
                                                  r::Situational, d::RepeatCount.bounded(1),
                                                  b::Element(e::Required, "Price Identifier Code", b::Values("WHL")),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A")),
                                       b::Segment(150, s::DTM, "Date/Time Reference",
                                                  r::Situational, d::RepeatCount.bounded(10),
                                                  b::Element(e::Required,    "Date/Time Qualifier", b::Values("002")),
                                                  b::Element(e::Situational, "Date"),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A"),
                                                  b::Element(e::NotUsed,  "N/A")),

                                       d::LoopDef.build("N1", d::RepeatCount.bounded(200),
                                                        b::Segment(310, s:: N1, "Name",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Required,    "Entity Identifier Code", b::Values("SF", "ST")),
                                                                   b::Element(e::Required,    "Name"),
                                                                   b::Element(e::Situational, "Identification Code Qualifier", b::Values("91")),
                                                                   b::Element(e::Situational, "Identification Code"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A")),
                                                        b::Segment(330, s:: N3, "Address Information",
                                                                   r::Situational, d::RepeatCount.bounded(2),
                                                                   b::Element(e::Required,    "Address Information"),
                                                                   b::Element(e::Situational, "Address Information")),
                                                        b::Segment(340, s:: N4, "Geographic Location",
                                                                   r::Situational, d::RepeatCount.unbounded,
                                                                   b::Element(e::Situational, "City Name"),
                                                                   b::Element(e::Situational, "State or Province Code"),
                                                                   b::Element(e::Situational, "Postal Code"),
                                                                   b::Element(e::Situational, "Country Code"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A")),
                                                        b::Segment(350, s::REF, "Reference Identification",
                                                                   r::Situational, d::RepeatCount.bounded(12),
                                                                   b::Element(e::Required,    "Reference Identification Qualifier", b::Values("DP")),
                                                                   b::Element(e::Situational, "Reference Identification"),
                                                                   b::Element(e::NotUsed, "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A")))),

                    d::TableDef.header("Detail",
                                       d::LoopDef.build("PO1", d::RepeatCount.bounded(100000),
                                                        b::Segment(10, s::PO1, "Baseline Item Data",
                                                                   r::Required, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Situational, "Assigned Identification"),
                                                                   b::Element(e::Situational, "Quantity Ordered"),
                                                                   b::Element(e::Situational, "Unit or Basis for Measurement Code", b::Values("CA", "EA", "LB")),
                                                                   b::Element(e::Situational, "Unit Price"),
                                                                   b::Element(e::Situational, "Basis of Unit Price Code", b::Values("PE","PP","UM")),
                                                                   b::Element(e::Situational, "Product/Service ID Qualifier", b::Values("VN", "VC")),
                                                                   b::Element(e::Situational, "Product/Service ID"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"))),
                                       d::LoopDef.build("PID", d::RepeatCount.bounded(1000),
                                                        b::Segment(50, s::PID, "Product/Item Description",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Required,    "Item Description Type", b::Values("F")),
                                                                   b::Element(e::Situational, "Product/Process Characteristic Code"),
                                                                   b::Element(e::Situational, "Agency Qualifier Code"),
                                                                   b::Element(e::Situational, "Product Description Code"),
                                                                   b::Element(e::Situational, "Description"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"),
                                                                   b::Element(e::NotUsed,  "N/A"))),
                                       d::LoopDef.build("N1", d::RepeatCount.bounded(200),
                                                        b::Segment(350, s:: N1, "Name",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Required,    "Entity Identifier Code", b::Values("SF", "ST")),
                                                                   b::Element(e::Required,    "Name"),
                                                                   b::Element(e::Situational, "Identification Code Qualifier", b::Values("91")),
                                                                   b::Element(e::Situational, "Identification Code"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A")),
                                                        b::Segment(370, s:: N3, "Address Information",
                                                                   r::Situational, d::RepeatCount.bounded(2),
                                                                   b::Element(e::Required,    "Address Information"),
                                                                   b::Element(e::Situational, "Address Information")),
                                                        b::Segment(380, s:: N4, "Geographic Location",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Situational, "City Name"),
                                                                   b::Element(e::Situational, "State or Province Code"),
                                                                   b::Element(e::Situational, "Postal Code"),
                                                                   b::Element(e::Situational, "Country Code"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A")))),

                    d::TableDef.header("Summary",
                                       d::LoopDef.build("CTT", d::RepeatCount.bounded(1),
                                                        b::Segment(10, s::CTT, "Transaction Totals",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Required,    "Number of Line Items"),
                                                                   b::Element(e::Situational, "Hash Total"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A"),
                                                                   b::Element(e::NotUsed,     "N/A")),
                                                        b::Segment(20, s::AMT, "Amount",
                                                                   r::Situational, d::RepeatCount.bounded(1),
                                                                   b::Element(e::Required,    "Amount Qualifier Code"),
                                                                   b::Element(e::Required,    "Monetary Amount"),
                                                                   b::Element(e::NotUsed,     "N/A"))),
                                       b::Segment(30, s:: SE, "Transaction Set Trailer",
                                                  r::Required, d::RepeatCount.bounded(1),
                                                  b::Element(e::Required,    "Number of Included Segments"),
                                                  b::Element(e::Required,    "Transaction Set Control Number"))))

        end
      end
    end
  end
end
